import java.util.*;

class KADANE{
  public static int Kadane(int[] arr){
		int max_so_far = Integer.MIN_VALUE;
		int max_ending_here = 0;
		int n = arr.length;
		
		for(int i = 0; i < n; i++){
			max_ending_here += arr[i];
			
			if(max_so_far < max_ending_here)
				max_so_far = max_ending_here;
			
			if(max_ending_here < 0)
				max_ending_here = 0;
		}
		
		return max_so_far;
	}
	
	public static void main(String[] args){
    int[] arr = {1, -2, 0, -4, 7, 8, 1, 0};
    int max_subarray_sum = Kadane(arr);
    System.out.pintln("Maximum generated by the subarray of array = " + max_subarray_sum);
  }
}
